apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch:
jobs:
    custom:
        delegates: rajnish-cloudbees/My-sample-go-app/.cloudbees/workflows/simple_custom_job.yaml
        with:
             param1: "asdf"
        timeout-minutes: 4320
