apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  custom:
    delegates: https://bitbucket.org/rajnish-cloudbees/my-sample-go-app/.cloudbees/workflows/my-workflow.yaml
    with:
      param1: "asdf"
    timeout-minutes: 3

  build:
    needs: custom
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world ${{ needs.custom.outputs.result }}"