apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: custom_job_workflow
on:
  workflow_dispatch:
jobs:
  custom-job:
    delegates: rajnish-cloudbees/My-sample-go-app/simple-custom-job.yaml@main
    with:
      param1: "param one value"
