apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch:
jobs:
  custom-job:
    delegates: .cloudbees/workflows/simple_custom_job.yaml
    with:
      param1: "param one value"
