apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch:
jobs:
    custom:
        delegates: mluzcabrera/customjobpoll/topollillo.yaml
        with:
            some-arg: ${{ vars.testpropertymlcb404 }}
        secrets:
            asecret: ${{ secrets.testsecret1 }}
        timeout-minutes: 4320
