apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: getEnv
on:
  workflow_call:
    inputs:
      ENV:
        type: choice
        options:
          - QA
          - PROD
        default: QA
jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "${{ inputs.ENV }}"
