apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: build

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: 0,5 * * * *

permissions:
  scm-token-own: read

jobs:
  build:
    steps:
    - id: checkout
      name: Get source code
      uses: cloudbees-io/checkout@v1
      
    - id: context
      name: Display context info
      uses: docker://alpine:latest
      run: |
        echo 'branch: ${{ cloudbees.scm.branch }}, ref: ${{ cloudbees.scm.ref }}'
