apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "**"
  workflow_dispatch:
    inputs:
      environment:
        type: string
jobs:
  build:
    environment: ${{ inputs.environment }}
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo ${{ job.environment }}
