apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: manual

on:
  workflow_dispatch:
    inputs:
      environment: 
        default: STAGING
        required: true
        description: environment test input
        type: string

jobs:
  job:
    environment: ${{ inputs.environment }}
    steps:
      - id: step
        uses: docker://alpine:3.17
        run: |
         echo ${{ job.environment }}
