apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: build

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - "**"
  workflow_dispatch:
  # schedule:
  #   - cron: 0,5 * * * *

permissions:
  scm-token-own: read
  scm-token-org: read

jobs:
  build:
    steps:
      - id: checkout
        name: Get source code
        uses: cloudbees-io/checkout@v1

      - id: configured-credentials
        name: configured-credentials
        uses: cloudbees-io/configure-git-global-credentials/.cloudbees/testing@main
        #uses: cloudbees-io/configure-git-global-credentials@v1
        env:
          RUNNER_DEBUG: "1"
        with:
          token: ${{ secrets.bb_dc_http_access_token_sample_common }}
          repositories: https://bitbucket.saas-preprod.beescloud.com/scm/test-bbdc-unify/sample-common.git

      - uses: docker://alpine:3.20
        name: Clone the private repo
        run: |
          apk update
          apk add git
          apk add openssh-client
          echo "=============== CLONE REPO ================================"
          git clone https://bitbucket.saas-preprod.beescloud.com/scm/test-bbdc-unify/sample-common.git
