apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: build

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - "**"
  workflow_dispatch:
  # schedule:
  #   - cron: 0,5 * * * *

permissions:
  scm-token-own: read
  scm-token-org: read

jobs:
  build:
    steps:
    - id: checkout
      name: Get source code
      uses: cloudbees-io/checkout@v1

    - id: configured-credentials
      name: configured-credentials
      uses: cloudbees-io/configure-git-global-credentials@v1

    - id: go-build
      uses: docker://golang:latest
      run: |
        go version && go test -v ./...

