apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My automation

on:
  workflow_dispatch: {}

jobs:
  build:
    steps:
      - name: action test
        uses: https://bitbucket.saas-preprod.beescloud.com/projects/TEST/repos/test-bbcd-ak/browse/.cloudbees/actions/custom-action@main
        with:
          arg-1: |
            Optimus Prime